baseURL = '/'
languageCode = 'en-us'
title = 'Mary Fortuna - Detroit Michigan Artist'
theme = 'dolls'

[params]
    author = "Andrew M McCall"
    description = "Mary Fortuna is a Detroit, Michigan Artist Currently Living in Traverse City, Michigan"
    opengraphdefault = "/images/site-assets/White_Rabbit_Girl_with_Green_Hat_2017.png"
    imgAltDefault = "Mary Fortuna is a Detroit, Michigan artist currently living in Traverse City, Michigan."


[[params.social]]
name = "facebook"
url = "https://www.facebook.com/mary.fortuna"
icon = "fa fa-facebook fa-2x"




[menu]
[[menu.main]]
identifier = '/'
name = 'Home'
url = '/'
weight = -210

[[menu.main]]
identifier = 'blog'
name = 'Blog'
url = '/blog/'
weight = -160

[[menu.main]]
identifier = 'about'
name = "About Mary Fortuna"
url = '/about/'
weight = -180


[[menu.main]]
identifier = 'contact'
name = 'Contact Mary'
url = '/contact/'
weight = -190


[[menu.main]]
identifier = 'gallery'
name = 'Gallery'
url = '/gallery/'
weight = -200

[[menu.main]]
identifier = 'links'
name = 'Links'
url = '/links/'
weight = -100

## Gallery Children

[[menu.main]]
identifier = 'masks'
name = 'Masks'
url = '/gallery/masks'
parent = 'gallery'

[[menu.main]]
identifier = 'animals-and-insects'
name = 'Animals & Insects'
url = '/gallery/animals-and-insects'
parent = 'gallery'
weight = -210

[[menu.main]]
identifier = 'collages'
name = 'Collages'
url = '/gallery/collages'
parent = 'gallery'
weight = -200

[[menu.main]]
identifier = 'commissions-and-kids-drawings'
name = "Commissions & Kid's Drawings"
url = '/gallery/commissions-and-kids-drawings'
parent = 'gallery'
weight = -190

[[menu.main]]
identifier = 'dolls'
name = 'Dolls'
url = '/gallery/dolls'
parent = 'gallery'
weight = -180

[[menu.main]]
identifier = 'felt-and-fabric-dolls'
name = 'Felt & Fabric'
url = '/gallery/dolls/felt-and-fabric-dolls'
parent = 'dolls'
weight = -210

[[menu.main]]
identifier = 'leather-dolls'
name = 'Leather Dolls'
url = '/gallery/dolls/leather-dolls'
parent = 'dolls'
weight = -210



